########################################
# CCTV EDGE CONFIGURATION
########################################

########################################
# MULTI CAMERA SETTINGS
########################################
# Format:
# "CAMERA_NAME|RTSP_URL"

CAMERAS=(
"cam1|rtsp://marojahanasdf:@M123asdfasdf@192.168.X.XX:554/stream2"
)

########################################
# LOCAL BUFFER DIRECTORY
########################################
LOCAL_DIR="/cctv/recordings"

########################################
# RCLONE REMOTE DESTINATION
########################################
REMOTE_NAME="gdrive:CCTV"

########################################
# RECORDING SETTINGS
########################################
SEGMENT_TIME=120
MIN_AGE_BUFFER=60

########################################
# RCLONE PERFORMANCE LIMITS
########################################
TPS_LIMIT=10
TRANSFERS=6
CHECKERS=10
# TPS_LIMIT=4
# TRANSFERS=1
# CHECKERS=2

########################################
# AUDIO MODE
########################################
# yes  = encode audio to AAC
# no   = disable audio (recommended for low CPU)
USE_AUDIO="yes"

########################################
# LOG DIRECTORY / (gak dipakai, langsung baca dari .out saja agar tidak membebani cpu)
########################################
# LOG_DIR="/var/log/cctv"
